In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
sns.get_dataset_names()

In [ ]:
data = sns.load_dataset('titanic')
data.head()

survived  pclass     sex   age  ...  deck  embark_town  alive  alone
0         0       3    male  22.0  ...   NaN  Southampton     no  False
1         1       1  female  38.0  ...     C    Cherbourg    yes  False
2         1       3  female  26.0  ...   NaN  Southampton    yes   True
3         1       1  female  35.0  ...     C  Southampton    yes  False
4         0       3    male  35.0  ...   NaN  Southampton     no   True

[5 rows x 15 columns]

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.6+ KB


In [ ]:
#### EDA

In [ ]:
data['pclass'].value_counts()

In [ ]:
data['survived'].value_counts()

In [ ]:
sns.countplot(x=data['survived'])
plt.show()

In [ ]:
sns.countplot(x=data['pclass'])
plt.show()

In [ ]:
sns.countplot(x=data['survived'],hue=data['pclass'])
plt.show()

In [ ]:
sns.countplot(x=data['survived'],hue=data['sex'])
plt.show()

In [ ]:
sns.countplot(x=data['survived'],hue=data['embarked'])
plt.show()

In [ ]:
data.columns

In [ ]:
col = ['class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone','fare']
data_1 = data.drop(col,axis=1)

In [ ]:
data_1.head()

survived  pclass     sex   age  sibsp  parch embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [ ]:
!pip install sweetviz

In [ ]:
import sweetviz as sv

In [ ]:
features = sv.FeatureConfig(skip="deck")

In [ ]:
report = sv.analyze(data,target_feat='survived',feat_cfg=features)

                                             |          | [  0%]   00:00 -> (? left)

In [ ]:
report.show_notebook()

In [ ]:
data_1.head()

survived  pclass     sex   age  sibsp  parch embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [ ]:
## Null Values

In [ ]:
data_1.isnull().sum()

In [ ]:
mean_age = round(data_1['age'].mean(),2)
mean_age

In [ ]:
data_1['age'] = data_1['age'].fillna(mean_age)

In [ ]:
data_1 = data_1.dropna()

In [ ]:
data_1.isnull().sum()

In [ ]:
len(data_1)

889

In [ ]:
data_1['embarked'].value_counts()

In [ ]:
### Label Encoding

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data_1['sex'] = le.fit_transform(data_1['sex'])
data_1['embarked'] = le.fit_transform(data_1['embarked'])

In [ ]:
data_1.head()

survived  pclass  sex   age  sibsp  parch  embarked
0         0       3    1  22.0      1      0         2
1         1       1    0  38.0      1      0         0
2         1       3    0  26.0      0      0         2
3         1       1    0  35.0      1      0         2
4         0       3    1  35.0      0      0         2

In [ ]:
data_1.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'embarked'], dtype='object')

In [ ]:
x = np.array(data_1[['pclass', 'sex', 'age', 'sibsp', 'parch', 'embarked']])
y = np.array(data_1['survived'])

In [ ]:
x.shape

(889, 6)

In [ ]:
y.shape

(889,)

In [ ]:
x

In [ ]:
y

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.80,random_state=3)

In [ ]:
pd.DataFrame(y).value_counts()

In [ ]:
pd.DataFrame(ytrain).value_counts()

In [ ]:
### Build the model
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 7,p=2)

In [ ]:
### Train the model
model.fit(xtrain,ytrain)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=7, p=2,
                     weights='uniform')

In [ ]:
ypred = model.predict(xtest)
ypred

array([1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0])

In [ ]:
ytest

array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0])

In [ ]:
#### Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(ytest,ypred)
cm

array([[102,   8],
       [ 27,  41]])

In [ ]:
(92+41)/(110+68)

0.7471910112359551

In [ ]:
from sklearn.metrics import accuracy_score
a = accuracy_score(ytest,ypred)
a

0.8033707865168539

In [ ]:
accuracy = []
for k in range(1,len(xtrain)):
  model1 = KNeighborsClassifier(n_neighbors = k,p=2)
  model1.fit(xtrain,ytrain)
  ypred1 = model1.predict(xtest)
  a1 = accuracy_score(ytest,ypred1)
  accuracy.append(a1)

In [ ]:
np.max(accuracy)

0.8033707865168539

In [ ]:
accuracy = []
for k in range(1,len(xtrain)):
  model1 = KNeighborsClassifier(n_neighbors = k,p=1)
  model1.fit(xtrain,ytrain)
  ypred1 = model1.predict(xtest)
  a1 = accuracy_score(ytest,ypred1)
  accuracy.append(a1)

In [ ]:
np.max(accuracy)

0.8033707865168539

In [ ]:
np.argmax(accuracy)

6

In [ ]:
accuracy

In [ ]:
## Assignment
iris = sns.load_dataset('iris')
iris.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
data.describe()

survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
data_1["New Age"] = ss.fit_transform(data_1[['age']])

In [ ]:
data_1.describe()

survived      pclass         sex  ...       parch    embarked       New Age
count  889.000000  889.000000  889.000000  ...  889.000000  889.000000  8.890000e+02
mean     0.382452    2.311586    0.649044  ...    0.382452    1.535433 -3.868297e-17
std      0.486260    0.834700    0.477538  ...    0.806761    0.792088  1.000563e+00
min      0.000000    1.000000    0.000000  ...    0.000000    0.000000 -2.255494e+00
25%      0.000000    2.000000    0.000000  ...    0.000000    1.000000 -5.905085e-01
50%      0.000000    3.000000    1.000000  ...    0.000000    2.000000  3.578250e-03
75%      1.000000    3.000000    1.000000  ...    0.000000    2.000000  4.124951e-01
max      1.000000    3.000000    1.000000  ...    6.000000    2.000000  3.884430e+00

[8 rows x 8 columns]