In [ ]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.feature_extraction.text import CountVectorizer
docs=["the house had a tiny little mouse ",
      "the cat saw the mouse",
      "the mouse ran away from the house",
      "the end of the mouse story"]
      

In [ ]:
cv=CountVectorizer()
word_count_vector=cv.fit(docs)
print(word_count_vector)
word_count_vector=cv.transform(docs)
print(word_count_vector)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)
  (0, 4)	1
  (0, 5)	1
  (0, 6)	1
  (0, 7)	1
  (0, 12)	1
  (0, 13)	1
  (1, 1)	1
  (1, 7)	1
  (1, 10)	1
  (1, 12)	2
  (2, 0)	1
  (2, 3)	1
  (2, 5)	1
  (2, 7)	1
  (2, 9)	1
  (2, 12)	2
  (3, 2)	1
  (3, 7)	1
  (3, 8)	1
  (3, 11)	1
  (3, 12)	2


In [ ]:
print("final vector"+str(word_count_vector.toarray()))

final vector[[0 0 0 0 1 1 1 1 0 0 0 0 1 1]
 [0 1 0 0 0 0 0 1 0 0 1 0 2 0]
 [1 0 0 1 0 1 0 1 0 1 0 0 2 0]
 [0 0 1 0 0 0 0 1 1 0 0 1 2 0]]


In [ ]:
print("total words count=",cv.vocabulary_)

total words count= {'the': 12, 'house': 5, 'had': 4, 'tiny': 13, 'little': 6, 'mouse': 7, 'cat': 1, 'saw': 10, 'ran': 9, 'away': 0, 'from': 3, 'end': 2, 'of': 8, 'story': 11}


In [ ]:
print(cv.get_feature_names())

['away', 'cat', 'end', 'from', 'had', 'house', 'little', 'mouse', 'of', 'ran', 'saw', 'story', 'the', 'tiny']


In [ ]:
tfid=TfidfTransformer(smooth_idf=True,use_idf=True)
tfid.fit(word_count_vector)
print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.91629073 1.51082562
 1.91629073 1.         1.91629073 1.91629073 1.91629073 1.91629073
 1.         1.91629073]


In [ ]:
tfidf_vector=tfid.transform(word_count_vector)
print(tfidf_vector.toarray())

[[0.         0.         0.         0.         0.48992364 0.38626142
  0.48992364 0.25566248 0.         0.         0.         0.
  0.25566248 0.48992364]
 [0.         0.54541547 0.         0.         0.         0.
  0.         0.28462042 0.         0.         0.54541547 0.
  0.56924084 0.        ]
 [0.44796747 0.         0.         0.44796747 0.         0.3531827
  0.         0.23376801 0.         0.44796747 0.         0.
  0.46753602 0.        ]
 [0.         0.         0.47882569 0.         0.         0.
  0.         0.24987111 0.47882569 0.         0.         0.47882569
  0.49974222 0.        ]]
